/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ServidorIdRouteImport } from './routes/servidor.$id'
import { Route as ServidorIdIndexRouteImport } from './routes/servidor.$id.index'
import { Route as ServidorIdTrabalhoRouteImport } from './routes/servidor.$id.trabalho'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ServidorIdRoute = ServidorIdRouteImport.update({
  id: '/servidor/$id',
  path: '/servidor/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ServidorIdIndexRoute = ServidorIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServidorIdRoute,
} as any)
const ServidorIdTrabalhoRoute = ServidorIdTrabalhoRouteImport.update({
  id: '/trabalho',
  path: '/trabalho',
  getParentRoute: () => ServidorIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/servidor/$id': typeof ServidorIdRouteWithChildren
  '/servidor/$id/trabalho': typeof ServidorIdTrabalhoRoute
  '/servidor/$id/': typeof ServidorIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/servidor/$id/trabalho': typeof ServidorIdTrabalhoRoute
  '/servidor/$id': typeof ServidorIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/servidor/$id': typeof ServidorIdRouteWithChildren
  '/servidor/$id/trabalho': typeof ServidorIdTrabalhoRoute
  '/servidor/$id/': typeof ServidorIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/servidor/$id'
    | '/servidor/$id/trabalho'
    | '/servidor/$id/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/servidor/$id/trabalho' | '/servidor/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/servidor/$id'
    | '/servidor/$id/trabalho'
    | '/servidor/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ServidorIdRoute: typeof ServidorIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servidor/$id': {
      id: '/servidor/$id'
      path: '/servidor/$id'
      fullPath: '/servidor/$id'
      preLoaderRoute: typeof ServidorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servidor/$id/': {
      id: '/servidor/$id/'
      path: '/'
      fullPath: '/servidor/$id/'
      preLoaderRoute: typeof ServidorIdIndexRouteImport
      parentRoute: typeof ServidorIdRoute
    }
    '/servidor/$id/trabalho': {
      id: '/servidor/$id/trabalho'
      path: '/trabalho'
      fullPath: '/servidor/$id/trabalho'
      preLoaderRoute: typeof ServidorIdTrabalhoRouteImport
      parentRoute: typeof ServidorIdRoute
    }
  }
}

interface ServidorIdRouteChildren {
  ServidorIdTrabalhoRoute: typeof ServidorIdTrabalhoRoute
  ServidorIdIndexRoute: typeof ServidorIdIndexRoute
}

const ServidorIdRouteChildren: ServidorIdRouteChildren = {
  ServidorIdTrabalhoRoute: ServidorIdTrabalhoRoute,
  ServidorIdIndexRoute: ServidorIdIndexRoute,
}

const ServidorIdRouteWithChildren = ServidorIdRoute._addFileChildren(
  ServidorIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ServidorIdRoute: ServidorIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
